import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Providers from "@/components/providers";

const montserrat = localFont({
  src: '../public/montserrat.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "УГС 09.00.00",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
        <body className={montserrat.className}>
            <Providers>
                {children}
            </Providers>
        </body>
    </html>
);
}