import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../globals.css";
import Providers from "@/components/providers";
import Aside from "@/components/aside";
import Header from "@/components/header";

const montserrat = localFont({
  src: '../montserrat.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "УГС 09.00.00",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
        <body className={montserrat.className}>
            <Providers>
                  <div className={`max-w-[1440px] min-h-full relative mx-auto`}>
                    <Aside />
                    <main className="border-box min-h-screen py-8 pb-[200px] overflow-hidden relative">
                    <Header />
                    {children}
                    </main>
                  </div>
            </Providers>
        </body>
    </html>
);
}
