import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./../globals.css";
import Aside from "@/components/aside";
import Header from "@/components/header"

const montserrat = localFont({
  src: '../../public/montserrat.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "УГС 09.00.00",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
      <div className={`max-w-[550px] min-h-full px-8 relative mx-auto`}>
        <main className="border-box min-h-screen py-8 pb-[200px] relative">
          {children}
        </main>
      </div>
      </body>
    </html>
  );
}
